name: Publish
on:
  push:
    ## only works on master branch
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
      - run: npm set config loglevel=info
      - run: npx can-npm-publish
      - name: Install
        run: npm ci
      - name: Publish
        ## prepublishOnly has done build and test tasks
        uses: JS-DevTools/npm-publish@v1
        with:
          token: "${{ secrets.NPM_AUTH_TOKEN }}"
      - name: Git-tag
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
